config-version = "2.7"

[bind]
ip = "0.0.0.0"
port = 25565

[online-mode]
true

[velocity]
forwarding-mode = "modern"
forwarding-secret-file = "forwarding.secret"

[servers]
lobby = "lobby:25565"
citybuild = "citybuild:25565"
islewars = "islewars:25565"

[try]
order = ["lobby", "citybuild", "islewars"]

[forced-hosts]

[advanced]
login-rate-limit = 500
compress = true
compress-threshold = 256
fast-io-mode = true
disable-modern-legacy-ping = true
announce-forge = false
kick-existing-players = false
ping-passthrough = "Minedesso"
support-forge = false
enable-player-address-logging = false
